
#DATA STRUCTURE
> map.3<-read.csv(file="/Users/aneesha/Desktop/irina/map.11.12.22.csv", sep=",", header=TRUE, row.names=1)
> str(map.3)
'data.frame':	1015 obs. of  23 variables:
 $ Cluster                                                                 : int  3 1 3 3 2 2 2 4 2 4 ...
 $ Did.you.pursue.further.training.after.placing.your.first.dental.implant.: Factor w/ 2 levels "No","Yes": 2 1 2 2 2 2 2 2 1 1 ...
 $ If.Yes..this.was.CE.                                                    : int  1 0 0 0 0 1 1 1 0 0 ...
 $ If.Yes..this.was..None                                                  : int  0 1 0 0 0 0 0 0 1 1 ...
 $ If.Yes..this.was..Other                                                 : int  0 0 1 1 1 0 0 0 0 0 ...
 $ If.Yes..this.was..Uni1yr                                                : int  0 0 0 0 0 0 0 0 0 0 ...
 $ If.Yes..this.was..Uni2yr                                                : int  0 0 0 0 0 0 0 0 0 0 ...
 $ If.Yes..this.was..Uni3yr                                                : int  0 0 0 0 0 0 0 0 0 0 ...
 $ If.Yes..this.was..                                                      : Factor w/ 6 levels "CE","None","Other",..: 1 2 3 3 3 1 1 1 2 2 ...
 $ Challenge.Anasthesia                                                    : int  1 1 1 1 1 0 0 0 0 0 ...
 $ Challenge.Implant.position                                              : int  0 0 0 0 0 1 1 1 1 1 ...
 $ Challenge.Incision                                                      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Challenge.No.information                                                : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Challenge.prep.osteotomy                                                : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Challenge.reflection                                                    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Challenge.suturing                                                      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Challenge.other                                                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Challenge                                                               : Factor w/ 8 levels "Anasthesia","Identificaton.of.implant.position",..: 1 1 1 1 1 2 2 2 2 2 ...
 $ Reflection.Ad.prep                                                      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Reflection.Some.prep                                                    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Reflection.not.prep                                                     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Reflection.no.infromation                                               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Reflection                                                              : Factor w/ 4 levels "Adequately.prepared",..: 1 1 1 1 1 1 1 1 1 1 ...


#DATA PARTITION- TYPE OF FURTHER EDUCATION
> mt<-as.data.frame(prop.table(table(map.3$If.Yes..this.was.., map.3$Cluster),1))
> str(mt)
'data.frame':	30 obs. of  3 variables:
 $ Var1: Factor w/ 6 levels "CE","None","Other",..: 1 2 3 4 5 6 1 2 3 4 ...
 $ Var2: Factor w/ 5 levels "1","2","3","4",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ Freq: num  0.1304 0.1181 0.1436 0.1064 0.0312 ... #BARPLOT
 l<-ggplot(data=mt, aes(x= mt$Var1, y=mt$Freq, fill=mt$Var2, alpha=0.9)) +geom_bar(stat='identity', size=0.15, colour="black", width=0.5)
 z<-l +scale_fill_manual(values=c("black", "red", "green", "blue", "pink"))
 > z<-z+labs(x="Type of Further Education", y="Proportion of Respondents")
> z+ theme(axis.text = element_text(size=8, color="black"), axis.title.x=element_text(size=9, color="grey21"), axis.title.y=element_text(size=9, color="grey21"), legend.text = element_text(size=9))


#DATA PARTITION- Challenge
>  ct<-as.data.frame(prop.table(table(map.3$Challenge, map.3$Cluster),1))
> 
> lc<-ggplot(data=ct, aes(x= ct$Var1, y=ct$Freq, fill=ct$Var2, alpha=0.9)) +geom_bar(stat='identity', size=0.15, colour="black", width=0.4)
> 
>  zc<-lc +scale_fill_manual(values=c("black", "red", "green", "blue", "pink"))
> 
> zc<-zc+labs(x="Type of Challenge Faced", y="Proportion of Respondents")
> zc+ theme(axis.text = element_text(size=9, color="black"), axis.title.x=element_text(size=9, color="grey21"), axis.title.y=element_text(size=9, color="grey21"), legend.text = element_text(size=9), axis.text.x=element_text(size=8, color="black", angle=60))

#DATA PARTITION REFLECTION
>  rt<-as.data.frame(prop.table(table(map.3$Reflection, map.3$Cluster),1))
> rc<-ggplot(data=rt, aes(x= rt$Var1, y=rt$Freq, fill=rt$Var2, alpha=0.9)) +geom_bar(stat='identity', size=0.15, colour="black", width=0.5)
> rc<-rc +scale_fill_manual(values=c("black", "red", "green", "blue", "pink"))
> rc<-rc+labs(x="Reflection on level of preparation", y="Proportion of Respondents")
> rc+ theme(axis.text = element_text(size=9, color="black"), axis.title.x=element_text(size=9, color="grey21"), axis.title.y=element_text(size=9, color="grey21"), legend.text = element_text(size=9), axis.text.x=element_text(size=8, color="black", angle=20))

#MAP-DISTRIBUTION OF RESPONDENTS
map2<-read.csv(file="/Users/aneesha/Desktop/irina/culster.country.coded.csv", sep=",", header=TRUE, row.names=1)
> tab.map<-as.data.frame(table(map2$ISO3Code))
> str(tab.map)
'data.frame':	84 obs. of  2 variables:
 $ Var1: Factor w/ 84 levels "AFG","ARE","AUS",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Freq: int  1 8 30 1 3 2 3 1 5 8 ...
> library('rworldmap')
> > mapped_data <- joinCountryData2Map(tab.map, joinCode = "ISO3", nameJoinColumn = "Var1")84 codes from your data successfully matched countries in the map
0 codes from your data failed to match with a country code in the map
160 codes from the map weren't represented in your data
> colnames(tab.map)=c("Var1", "Number of Responders")
> par(mar=c(1,0.5,1.1,0.5), cex.main=0.9, cex.lab=0.8, cex.axis=0.8, cex.sub=0.8)
>  mapCountryData(mapped_data, nameColumnToPlot = "Number of Respondents", colourPalette="white2Black", missingCountryCol='white', borderCol="black")
> mapCountryData(mapped_data, nameColumnToPlot = "Number of Respondents", colourPalette="heat", missingCountryCol='grey', borderCol="black")
> mapCountryData(mapped_data, nameColumnToPlot = "Number of Respondents", colourPalette="topo", missingCountryCol='grey',borderCol='black')
